In [83]:

# llm_type=full ---> for complete architecture
# llm_type=enc ---> for encoder only architecture
# llm_type=dec ---> for decoder only architecture

#parameters with architecture and not during training 

def llm_parameters(dm,dec_n,enc_n,dff,enc_voc,dec_voc,llm_type:str):

    
    #encoding layer     2 parameters for layer normalization in MHA, FFN
    
    #.......encoder embedding.........
    enc_emb=enc_voc*dm
    #.......multi-head attention..........
    enc_mha=(dm+1)*dm*4+2 # for Q, K, V, O ,
    #.......feed forward network........
    enc_ffn=(dm+1)*dff+(dff+1)*dm+2  
    #.......total parameters in encoder layer........
    enc_p=enc_emb+enc_n*(enc_mha+enc_ffn)

    #decoding layer      2 parameters for layer normalization in masked-MHA, MHA, FFN
    #.........decoder embedding...........
    dec_emb=dec_voc*dm
    #.........masked multi-head attention...........
    dec_mmha=(dm+1)*dm*4+2  # for Q, K, V, O
    #.........multi-head attention...............
    dec_mha=(dm+1)*dm*4+2 # for Q, K, V, O
    #.........feed forward network............
    dec_ffn=(dm+1)*dff+(dff+1)*dm+2
    #.........Final linear layer before softmax output..........
    dec_lin=(dm+1)*dec_voc
    
    parameters=0

    if llm_type=="full":
        parameters=enc_p+dec_emb+(dec_mmha+dec_mha+dec_ffn)*dec_n+dec_lin
        print("__________________________________________________________________")
        print("Layer (type)                Output Shape              Param #     ")
        print("------------------------------------------------------------------")
        print("Encoder                       multiple                "+str(enc_p))
        print("Decoder                       multiple                "+str(parameters-enc_p-dec_lin))
        print("Dense                         multiple                "+str(dec_lin))
        print("__________________________________________________________________")
        print("Total parameters="+str(parameters)+" ("+str((parameters*4)/1e6)+" MB)")
        print("------------------------------------------------------------------")

    if llm_type=="enc":
        print("parameters="+str(enc_p))

    if llm_type=="dec":
        parameters=dec_emb+(dec_mmha+dec_ffn)*dec_n+dec_lin
        print("parameters="+str(parameters)+" ("+str((parameters*4)/1e6)+" MB)")
        print("percentage for "+"embed="+str(round(dec_emb*100/parameters,2))+"% multihead="+str(round(dec_mmha*dec_n*100/parameters,2))+"% FFN="+str(round(dec_ffn*dec_n*100/parameters,2))+"% linear="+str(round(dec_lin*100/parameters,2))+"%")    
    


In [84]:
dm=12288
dec_n=96
enc_n=96
dff=4*dm
enc_voc=8568
dec_voc=50257
llm_type="dec"

llm_parameters(dm,dec_n,enc_n,dff,enc_voc,dec_voc,llm_type)


parameters=175191958993 (700767.835972 MB)
percentage for embed=0.35% multihead=33.1% FFN=66.2% linear=0.35%


In [85]:
dm=5140
dec_n=40
enc_n=40
dff=4*dm
enc_voc=8568
dec_voc=50257
llm_type="dec"

llm_parameters(dm,dec_n,enc_n,dff,enc_voc,dec_voc,llm_type)


parameters=13199950777 (52799.803108 MB)
percentage for embed=1.96% multihead=32.03% FFN=64.06% linear=1.96%


In [86]:
dm=4096
dec_n=32
enc_n=32
dff=4*dm
enc_voc=8568
dec_voc=50257
llm_type="dec"

llm_parameters(dm,dec_n,enc_n,dff,enc_voc,dec_voc,llm_type)

parameters=6855386321 (27421.545284 MB)
percentage for embed=3.0% multihead=31.33% FFN=62.66% linear=3.0%


In [87]:
dm=2560
dec_n=32
enc_n=32
dff=4*dm
enc_voc=8568
dec_voc=50257
llm_type="dec"

llm_parameters(dm,dec_n,enc_n,dff,enc_voc,dec_voc,llm_type)

parameters=2774685905 (11098.74362 MB)
percentage for embed=4.64% multihead=30.24% FFN=60.48% linear=4.64%


In [88]:
dm=2048
dec_n=24
enc_n=24
dff=4*dm
enc_voc=8568
dec_voc=50257
llm_type="dec"

llm_parameters(dm,dec_n,enc_n,dff,enc_voc,dec_voc,llm_type)

parameters=1414304945 (5657.21978 MB)
percentage for embed=7.28% multihead=28.48% FFN=56.96% linear=7.28%


In [89]:
dm=1536
dec_n=24
enc_n=24
dff=4*dm
enc_voc=8568
dec_voc=50257
llm_type="dec"

llm_parameters(dm,dec_n,enc_n,dff,enc_voc,dec_voc,llm_type)

parameters=834248881 (3336.995524 MB)
percentage for embed=9.25% multihead=27.17% FFN=54.32% linear=9.26%


In [90]:
dm=1024
dec_n=24
enc_n=24
dff=4*dm
enc_voc=8568
dec_voc=50257
llm_type="dec"

llm_parameters(dm,dec_n,enc_n,dff,enc_voc,dec_voc,llm_type)

parameters=405187761 (1620.751044 MB)
percentage for embed=12.7% multihead=24.87% FFN=49.72% linear=12.71%


In [91]:
dm=768
dec_n=12
enc_n=12
dff=4*dm
enc_voc=8568
dec_voc=50257
llm_type="dec"

llm_parameters(dm,dec_n,enc_n,dff,enc_voc,dec_voc,llm_type)

parameters=162262657 (649.050628 MB)
percentage for embed=23.79% multihead=17.47% FFN=34.92% linear=23.82%


percentage for embed=0.35% multihead=33.1% FFN=66.2% linear=0.35%
percentage for embed=1.96% multihead=32.03% FFN=64.06% linear=1.96%
percentage for embed=3.0% multihead=31.33% FFN=62.66% linear=3.0%
percentage for embed=4.64% multihead=30.24% FFN=60.48% linear=4.64%
percentage for embed=7.28% multihead=28.48% FFN=56.96% linear=7.28%
percentage for embed=9.25% multihead=27.17% FFN=54.32% linear=9.26%
percentage for embed=12.7% multihead=24.87% FFN=49.72% linear=12.71%
percentage for embed=23.79% multihead=17.47% FFN=34.92% linear=23.82%

In [ ]:
percentage for embed=0.35% multihead=33.1% FFN=66.2% linear=0.35%
percentage for embed=1.96% multihead=32.03% FFN=64.06% linear=1.96%
percentage for embed=3.0% multihead=31.33% FFN=62.66% linear=3.0%
percentage for embed=4.64% multihead=30.24% FFN=60.48% linear=4.64%
percentage for embed=7.28% multihead=28.48% FFN=56.96% linear=7.28%
percentage for embed=9.25% multihead=27.17% FFN=54.32% linear=9.26%
percentage for embed=12.7% multihead=24.87% FFN=49.72% linear=12.71%
percentage for embed=23.79% multihead=17.47% FFN=34.92% linear=23.82%